apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: frontend-hospital
  name: frontend-hospital-deployment
  namespace: envi-name
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50%
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: frontend-hospital
  template:
    metadata:
      labels:
        app: frontend-hospital
      namespace: envi-name
    spec:
      containers:
        - image: dynamic-image
          imagePullPolicy: Always
          name: frontend-hospital
          ports:
            - containerPort: 80
              name: tcp
              protocol: TCP
          resources:
            limits:
              cpu: 500m
              memory: 800Mi
            requests:
              cpu: 300m
              memory: 400Mi
          securityContext:
            allowPrivilegeEscalation: true
            runAsGroup: 0
            runAsUser: 0
