# Sử dụng Node.js phiên bản mới nhất hỗ trợ Angular
FROM node:18-alpine

# Chuyển đến thư mục ứng dụng trong container
WORKDIR /app

# Copy package.json và package-lock.json (hoặc yarn.lock nếu dùng Yarn)
COPY package*.json ./

# Cài đặt các dependencies của dự án
RUN npm install

RUN npm install -g @angular/cli

# Copy phần còn lại của mã nguồn
COPY . .

# Chạy build ứng dụng Angular và tạo thư mục dist/
RUN npm run build --prod

