FROM node:18.19-alpine

# Cài đặt Angular CLI toàn cục
RUN npm install -g @angular/cli

# Chuyển đến thư mục ứng dụng trong container
WORKDIR /app

# Copy package.json và package-lock.json vào container
COPY package*.json ./

# Cài đặt các dependencies của dự án
RUN npm install

# Copy phần còn lại của mã nguồn
COPY . .

# Chạy build ứng dụng Angular
RUN npm run build --prod
